name: "Check for changes in OpenApi specifications"
on:
  schedule:
  - cron: "10 0 * * *"

jobs:
  CheckVersion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js latest version
      uses: actions/setup-node@v1
    - run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
    - run: npm run build --if-present
    - run: npm run cloneOas
    - run: npm run checkOasVersions
    
