# this workflow runs a check on the collection of APIs at https://apis.guru/
# if more than one specification is present per API it will only check the lastest
# about 2200 specifications are checked this way
# The job failes if it finds specifications that do not match the relevant openApi JSON schema 
# and for which no previous failure is known in /test/realworld/failed.json
#
name: "Real world API test"

on:
  schedule:
    # once week on thursday 
    - cron: '19 16 * * 4'
  workflow_dispatch:
    inputs:
      delay:
        description: Delay in micro seconds between requests
        required: false
        default: 100

jobs:
 realWorldTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js latest version
      uses: actions/setup-node@v1
    - run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
    - run: npm run build --if-present
    - name: Start the test
      env: 
        GITHUB_EVENT_INPUTS_DELAY: ${{ github.event.inputs.delay }}
      run: npm run realWorldTestCI
    - name: push changes to remote
      run: |
        git add test/realworld/failed*
        git \
        -c user.name="GitHub Actions" \
        -c user.email="actions@github.com" \
        commit -m "Updated Real World test report on `date +%F`" \
        --author "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" \
        || echo "Nothing to commit, proceeding"
        git push
